### ISSUE TITLE
Portal Safety causes preview images to not load

### ISSUE THREAD

**Issue by tinkkis5** [Yaekith/EthosClient#15]
This applies to world, avatar and social tabs, avatar pedestals and portals.
Also tested this without emmvrc loaded at the same time and it still happens.

**Off:**
![image](https://user-images.githubusercontent.com/41975260/89413494-94521c80-d731-11ea-9285-90e9141bc220.png)

**On:**
![image](https://user-images.githubusercontent.com/41975260/89413599-c499bb00-d731-11ea-92ae-b1acfdb48a75.png)

**Comment by LonelyLuni** [comment]
Portal safety blocks malicious links from loading and is not working properly right now. For now just turn it off.
