### ISSUE TITLE
Portal Safety Issue

### ISSUE THREAD

**Issue by CronaTV** [Yaekith/EthosClient#17]
One of the problems I had was when walking through a portal with the "Confirm portal" safety on, it would send me to the world but a completely random public instance. I know it wasn't the one I walked into the portal for because friend's are dropping them, to friends+ instances, but it's dropping me in public instances. Turning the setting off fixes it, so I'm sure it's the one causing the problem

**Comment by Yaekith** [comment]
Never had this issue before but I'll look into it, thanks.
